- name: show  TOP10 CPU  && MEMORY 
  hosts: all
  tasks:
    - name: SHOW TOP10
      shell:
        /usr/bin/ps auxw | /usr/bin/head -1;/usr/bin/ps auxw | /usr/bin/sort -rn -k3 | /usr/bin/head -10
        /usr/bin/ps auxw | /usr/bin/head -1;/usr/bin/ps auxw| /usr/bin/sort -rn -k4 | /usr/bin/head -10
 
